# Generated by Django 2.0.5 on 2018-06-02 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone numbers must be in +380 XX XXX XXXX', regex='^\\+380\\s\\d{2}\\s\\d{3}\\s\\d{4}$')], verbose_name='Phone')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('address_en', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('address_ru', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('address_uk', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone numbers must be in +380 XX XXX XXXX', regex='^\\+380\\s\\d{2}\\s\\d{3}\\s\\d{4}$')], verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
