# Generated by Django 2.0.5 on 2018-06-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude_en',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude_ru',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude_uk',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude_en',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude_ru',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude_uk',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
    ]
