# Generated by Django 2.0.5 on 2018-06-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180602_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='latitude_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='latitude_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='latitude_uk',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude_uk',
        ),
    ]
