# Generated by Django 2.0.5 on 2018-06-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180602_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='latitude',
            field=models.CharField(max_length=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='longitude',
            field=models.CharField(max_length=10, verbose_name='Longitude'),
        ),
    ]
