# Generated by Django 2.0.5 on 2018-06-04 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20180603_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone numbers must be in +380 XX XXX XXXX', regex='^\\+380\\s\\d{2}\\s\\d{3}\\s\\d{4}$')], verbose_name='Phone'),
        ),
    ]
