# Generated by Django 2.1 on 2018-08-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20180604_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_uk',
        ),
    ]
