# Generated by Django 2.1 on 2018-08-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20180814_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
