# Generated by Django 2.1 on 2018-08-14 20:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Phone'),
        ),
    ]
