# Generated by Django 2.0.5 on 2018-06-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180520_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='post',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
