# Generated by Django 2.1.1 on 2018-10-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Computers'), ('2', 'Laptops'), ('3', 'Cameras'), ('4', 'Hardware'), ('5', 'Smartphones'), ('6', 'TV & Audio'), ('7', 'Gadgets'), ('8', 'Car Electronics'), ('9', 'Videogames'), ('10', 'Accessories')], max_length=2, verbose_name='Category')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url-label')),
                ('color', models.CharField(choices=[('#000000', 'Black'), ('#FFFFFF', 'White'), ('#808080', 'Gray'), ('#A52A2A', 'Brown'), ('#FF0000', 'Red'), ('#008000', 'Green'), ('#0000FF', 'Blue'), ('#FFFF00', 'Yellow')], max_length=7, verbose_name='Product color')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_images/', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product', verbose_name='Product')),
            ],
        ),
    ]
